baseURL = "http://darshancrout.ai/"
languageCode = "en-us"
title = "Home"

theme="simple-hugo-theme"

# Pagination
paginate=3
paginatePath="page"

# Highlighting
pygmentsCodefences=true
pygmentsCodeFencesGuessSyntax=true
pygmentsoptions="linenos=table"
pygmentsStyle="vs"

# Copyright
copyright="© 2019 — Darshan Crout — All rights reserved."

# Menu
  # Header
  [[menu.main]]
    url="/about/"
    name="About"
    weight=1
  [[menu.main]]
    url="/posts/"
    name="Blog"
    weight=2
  [[menu.main]]
    url="/now/"
    name="Now"
    weight=3
  [[menu.main]]
    url="/setup/"
    name="Setup"
    weight=4
  # Footer
  [[menu.footer]]
    url="https://github.com/dtcrout"
    name="GitHub"
    weight=1
  [[menu.footer]]
    url="https://www.linkedin.com/in/darshancrout/"
    name="LinkedIn"
    weight=2
  [[menu.footer]]
    url="https://open.spotify.com/user/iedy3su2rmbflgr9tw3tu52zk?si=O-y6clQhQmadsasQCnPUTQ"
    name="Spotify"
    weight=3

# Links format
[permalinks]
  post="/post/:year/:month/:title/"