title: Darshan Crout
email: dtcrout@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Data scientist, tech enthusiast and amateur music nerd.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dtcrout

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
